### ISSUE TITLE
Freezing/Crashing after 'Favouriting' series'

### ISSUE THREAD

**Issue by NaJ4Ri** [amgart/iracingPlanner#99]
I selected all of the Class C - sports and formula series since they are relevant to me currently hoping to filter out other series. In doing so when I clicked back on dashboard the program essentially froze up. When rebooting program just shows a blank screen

**Comment by NaJ4Ri** [comment]
Hi thank you for such a fast response, I did as you mentioned and it did indeed start working again, i then tried just selecting one series as a favourite and clicked back to dashboard, which worked but did considerably slow down the program. And as I added more and more favourites the app got slower and slower to respond to the point it was unusable so I think I may just not favourite any series and try use it that way. I can provide you anything you need to perhaps investigate if you would like. I would be very surprised if it was a hardware issue as I have 32gb RAM @ 3600Mhz, i5 10600k, plenty of storage and a 4070. Thanks again.

**Comment by amgart** [comment]
Hi again @NaJ4Ri ,
I am sorry that this can be a problem for you. If you could try without setting favorite content until I found a solution would be great.
I will get back to you when I identify and solve the issue :)

Again, thank you so much for using the app and hope this is not a big problem meanwhile.
Regards!
